Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 5
  Exclude:
    - "**/*_spec.rb"
Metrics/ParameterLists:
  Max: 4
